export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';
export const SORT_ITEMS = 'SORT_ITEMS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_BRAND_FILTER = 'ADD_BRAND_FILTER';
export const REMOVE_BRAND_FILTER = 'REMOVE_BRAND_FILTER';
export const ADD_TAG_FILTER = 'ADD_TAG_FILTER';
export const REMOVE_TAG_FILTER = 'REMOVE_TAG_FILTER';

