export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';
export const SORT_ITEMS = 'SORT_ITEMS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const FILTER_ITEMS_BY_BRANDS = 'FILTER_ITEMS_BY_BRANDS';
export const FILTER_ITEMS_BY_TAGS = 'FILTER_ITEMS_BY_TAGS';
